#!/usr/bin/env python3
"""단어 DB 초기화 — Word1(주제어), Word2(수식어풀) JSON 생성"""
import json
from pathlib import Path

CONFIG_DIR = Path(__file__).parents[4] / "config"
WORD1_FILE = CONFIG_DIR / "word1-db.json"
WORD2_FILE = CONFIG_DIR / "word2-pool.json"

WORD1_DB = {
    "감정": [
        {"word": "사랑", "en": "love, tender warmth, longing"},
        {"word": "평화", "en": "peace, serenity, stillness"},
        {"word": "희망", "en": "hope, anticipation, dawn"},
        {"word": "자유", "en": "freedom, liberation, open sky"},
        {"word": "슬픔", "en": "sorrow, melancholy, quiet tears"},
        {"word": "기쁨", "en": "joy, elation, radiant happiness"},
        {"word": "외로움", "en": "loneliness, solitude, distant echo"},
        {"word": "설렘", "en": "excitement, fluttering anticipation"},
        {"word": "그리움", "en": "yearning, nostalgia, distant memory"},
        {"word": "분노", "en": "rage, fierce storm, burning intensity"},
        {"word": "경이", "en": "wonder, awe, breathtaking marvel"},
        {"word": "두려움", "en": "fear, shadowy dread, trembling darkness"},
        {"word": "감사", "en": "gratitude, warmth, golden light"},
        {"word": "용기", "en": "courage, bold flame, unyielding spirit"},
        {"word": "황홀", "en": "ecstasy, transcendence, blissful dissolution"},
        {"word": "공허", "en": "emptiness, void, hollow silence"},
        {"word": "평온", "en": "tranquility, still water, calm breath"},
        {"word": "열정", "en": "passion, blazing desire, unstoppable drive"},
        {"word": "질투", "en": "jealousy, green fire, burning envy"},
        {"word": "수치", "en": "shame, hidden darkness, faded bloom"}
    ],
    "자연": [
        {"word": "바다", "en": "ocean, vast depth, endless waves"},
        {"word": "숲", "en": "forest, ancient canopy, dappled light"},
        {"word": "달", "en": "moon, silver glow, night guardian"},
        {"word": "별", "en": "stars, cosmos, sparkling infinity"},
        {"word": "안개", "en": "fog, misty veil, soft mystery"},
        {"word": "빛", "en": "light, radiant beam, golden warmth"},
        {"word": "구름", "en": "clouds, drifting shapes, sky canvas"},
        {"word": "폭풍", "en": "storm, fierce tempest, electric sky"},
        {"word": "눈", "en": "snow, pure white, silent blanket"},
        {"word": "불꽃", "en": "flame, dancing fire, crackling warmth"},
        {"word": "바람", "en": "wind, invisible force, rustling leaves"},
        {"word": "비", "en": "rain, rhythmic drops, earthy scent"},
        {"word": "새벽", "en": "dawn, first light, quiet awakening"},
        {"word": "황혼", "en": "dusk, fading gold, evening melancholy"},
        {"word": "얼음", "en": "ice, crystalline cold, frozen time"},
        {"word": "강", "en": "river, flowing journey, carved valley"},
        {"word": "산", "en": "mountain, towering peak, ancient stone"},
        {"word": "사막", "en": "desert, endless sand, scorching silence"},
        {"word": "초원", "en": "meadow, swaying grass, open horizon"},
        {"word": "하늘", "en": "sky, boundless blue, infinite expanse"}
    ],
    "판타지": [
        {"word": "용", "en": "dragon, mythical beast, ancient power"},
        {"word": "마법", "en": "magic, arcane spell, shimmering enchantment"},
        {"word": "요정", "en": "fairy, ethereal wings, woodland spirit"},
        {"word": "유령", "en": "ghost, transparent specter, lingering soul"},
        {"word": "천사", "en": "angel, divine wings, radiant halo"},
        {"word": "악마", "en": "demon, dark power, shadowy temptation"},
        {"word": "전사", "en": "warrior, battle-hardened, iron will"},
        {"word": "마녀", "en": "witch, mysterious power, midnight cauldron"},
        {"word": "신화", "en": "myth, legendary tale, timeless legend"},
        {"word": "결정체", "en": "crystal, prismatic facets, pure energy"},
        {"word": "포탈", "en": "portal, dimensional gateway, swirling vortex"},
        {"word": "고대", "en": "ancient, primordial, timeworn mystery"},
        {"word": "예언", "en": "prophecy, fated vision, oracle whisper"},
        {"word": "성역", "en": "sanctuary, sacred space, divine refuge"},
        {"word": "심연", "en": "abyss, unfathomable depth, dark beyond"},
        {"word": "불사", "en": "immortal, undying, eternal existence"},
        {"word": "변신", "en": "metamorphosis, transformation, shifting form"},
        {"word": "소환", "en": "summoning, mystical call, bound spirit"},
        {"word": "마계", "en": "underworld, shadow realm, infernal domain"},
        {"word": "봉인", "en": "seal, bound power, contained force"}
    ],
    "일상": [
        {"word": "커피", "en": "coffee, morning ritual, bitter warmth"},
        {"word": "고양이", "en": "cat, curious grace, soft mystery"},
        {"word": "책", "en": "book, infinite worlds, paper wisdom"},
        {"word": "음악", "en": "music, resonant harmony, soul melody"},
        {"word": "여행", "en": "journey, wandering spirit, distant horizon"},
        {"word": "꽃", "en": "flower, delicate bloom, fleeting beauty"},
        {"word": "도시", "en": "city, neon pulse, concrete labyrinth"},
        {"word": "창문", "en": "window, framed world, liminal view"},
        {"word": "기억", "en": "memory, faded photograph, echo of past"},
        {"word": "편지", "en": "letter, handwritten words, paper emotion"},
        {"word": "시계", "en": "clock, ticking time, measured existence"},
        {"word": "거울", "en": "mirror, reflected truth, parallel world"},
        {"word": "침묵", "en": "silence, unspoken words, listening void"},
        {"word": "빵", "en": "bread, humble nourishment, daily comfort"},
        {"word": "새", "en": "bird, free flight, morning song"},
        {"word": "계단", "en": "staircase, ascending journey, threshold crossing"},
        {"word": "열쇠", "en": "key, unlocking potential, secret passage"},
        {"word": "그림자", "en": "shadow, dark companion, silhouette truth"},
        {"word": "향기", "en": "fragrance, invisible presence, sensory memory"},
        {"word": "식사", "en": "meal, shared warmth, nourishing gathering"}
    ],
    "추상": [
        {"word": "시간", "en": "time, ceaseless flow, measured eternity"},
        {"word": "꿈", "en": "dream, surreal landscape, sleeping vision"},
        {"word": "무한", "en": "infinity, boundless, endless recursion"},
        {"word": "균형", "en": "balance, harmonious tension, perfect equilibrium"},
        {"word": "변화", "en": "change, constant flux, evolving form"},
        {"word": "순환", "en": "cycle, eternal return, revolving pattern"},
        {"word": "경계", "en": "boundary, liminal edge, threshold"},
        {"word": "연결", "en": "connection, invisible threads, woven bond"},
        {"word": "해방", "en": "liberation, breaking free, soaring release"},
        {"word": "창조", "en": "creation, birth of form, generative force"},
        {"word": "소멸", "en": "dissolution, fading into nothing, graceful end"},
        {"word": "조화", "en": "harmony, resonant unity, balanced beauty"},
        {"word": "혼돈", "en": "chaos, swirling disorder, primal energy"},
        {"word": "진실", "en": "truth, naked clarity, undeniable core"},
        {"word": "환상", "en": "illusion, shifting mirage, beautiful deception"},
        {"word": "존재", "en": "existence, being itself, fundamental presence"},
        {"word": "공간", "en": "space, void between, containing emptiness"},
        {"word": "기원", "en": "origin, first moment, primordial beginning"},
        {"word": "운명", "en": "fate, predetermined path, cosmic design"},
        {"word": "의지", "en": "will, determined force, purposeful drive"}
    ]
}

WORD2_POOL = [
    {"word": "우산", "en": "umbrella, shelter from storm"},
    {"word": "톱니바퀴", "en": "gear, clockwork mechanism"},
    {"word": "해파리", "en": "jellyfish, drifting translucence"},
    {"word": "열쇠", "en": "key, unlocking mystery"},
    {"word": "나침반", "en": "compass, guiding direction"},
    {"word": "모래시계", "en": "hourglass, flowing time"},
    {"word": "거울", "en": "mirror, reflective surface"},
    {"word": "촛불", "en": "candle, warm flickering light"},
    {"word": "나비", "en": "butterfly, metamorphic beauty"},
    {"word": "뿌리", "en": "roots, deep foundation"},
    {"word": "유리구슬", "en": "glass marble, captured world"},
    {"word": "실", "en": "thread, connecting line"},
    {"word": "조개껍질", "en": "seashell, ocean memory"},
    {"word": "깃털", "en": "feather, light as air"},
    {"word": "수정", "en": "crystal, prismatic clarity"},
    {"word": "사슬", "en": "chain, linked constraint"},
    {"word": "종이배", "en": "paper boat, fragile journey"},
    {"word": "별자리", "en": "constellation, mapped stars"},
    {"word": "계단", "en": "staircase, ascending path"},
    {"word": "문", "en": "door, threshold gateway"},
    {"word": "탑", "en": "tower, solitary height"},
    {"word": "다리", "en": "bridge, connecting span"},
    {"word": "미로", "en": "labyrinth, winding mystery"},
    {"word": "폐허", "en": "ruins, forgotten glory"},
    {"word": "도서관", "en": "library, knowledge repository"},
    {"word": "수중", "en": "underwater, submerged world"},
    {"word": "우주", "en": "cosmos, stellar expanse"},
    {"word": "화산", "en": "volcano, molten fury"},
    {"word": "동굴", "en": "cave, hidden depths"},
    {"word": "빙하", "en": "glacier, ancient ice"},
    {"word": "녹슨", "en": "rusty, weathered decay"},
    {"word": "투명한", "en": "transparent, see-through clarity"},
    {"word": "거대한", "en": "colossal, overwhelming scale"},
    {"word": "미세한", "en": "microscopic, tiny intricacy"},
    {"word": "녹아내리는", "en": "melting, dissolving form"},
    {"word": "떠오르는", "en": "rising, ascending emergence"},
    {"word": "부서지는", "en": "shattering, explosive break"},
    {"word": "꼬인", "en": "twisted, contorted shape"},
    {"word": "빛나는", "en": "glowing, luminous radiance"},
    {"word": "소용돌이", "en": "vortex, spiraling force"},
    {"word": "연기", "en": "smoke, wisping trail"},
    {"word": "물거품", "en": "bubble, fleeting sphere"},
    {"word": "결빙", "en": "frost, crystalline cold"},
    {"word": "낙엽", "en": "fallen leaf, autumnal end"},
    {"word": "씨앗", "en": "seed, potential life"},
    {"word": "균사", "en": "mycelium, underground network"},
    {"word": "산호", "en": "coral, ocean colony"},
    {"word": "날개", "en": "wing, flight mechanism"},
    {"word": "눈동자", "en": "eye pupil, seeing center"},
    {"word": "신경망", "en": "neural net, branching signals"},
    {"word": "기계팔", "en": "mechanical arm, robotic limb"},
    {"word": "회로", "en": "circuit, electronic pathway"},
    {"word": "프리즘", "en": "prism, light splitter"},
    {"word": "만화경", "en": "kaleidoscope, symmetrical pattern"},
    {"word": "홀로그램", "en": "hologram, 3D projection"},
    {"word": "블랙홀", "en": "black hole, event horizon"},
    {"word": "성운", "en": "nebula, stellar nursery"},
    {"word": "오로라", "en": "aurora, atmospheric dance"},
    {"word": "번개", "en": "lightning, electric strike"},
    {"word": "폭포", "en": "waterfall, cascading drop"},
    {"word": "바위", "en": "rock, ancient solid"},
    {"word": "용암", "en": "lava, molten rock"},
    {"word": "화석", "en": "fossil, time-preserved life"},
    {"word": "호박", "en": "amber, trapped moment"},
    {"word": "해골", "en": "skeleton, bare structure"},
    {"word": "왕관", "en": "crown, sovereign symbol"},
    {"word": "칼", "en": "sword, decisive edge"},
    {"word": "마스크", "en": "mask, hidden face"},
    {"word": "인형", "en": "doll, miniature human"},
    {"word": "시계탑", "en": "clock tower, time monument"},
    {"word": "등대", "en": "lighthouse, guiding beacon"},
    {"word": "온실", "en": "greenhouse, sheltered growth"},
    {"word": "천문대", "en": "observatory, sky watcher"},
    {"word": "비행선", "en": "airship, floating vessel"},
    {"word": "잠수함", "en": "submarine, deep diver"},
    {"word": "우주선", "en": "spacecraft, cosmic vessel"},
    {"word": "터널", "en": "tunnel, passage through"},
    {"word": "지도", "en": "map, charted territory"},
    {"word": "악보", "en": "sheet music, written sound"},
    {"word": "암호", "en": "cipher, coded message"},
    {"word": "문신", "en": "tattoo, skin inscription"},
    {"word": "혈관", "en": "vein, life channel"},
    {"word": "심장", "en": "heart, vital core"},
    {"word": "눈물", "en": "tear, emotional liquid"},
    {"word": "거미줄", "en": "spider web, geometric trap"},
    {"word": "덩굴", "en": "vine, climbing growth"},
    {"word": "이끼", "en": "moss, soft covering"},
    {"word": "버섯", "en": "mushroom, forest dweller"},
    {"word": "가시", "en": "thorn, protective spike"},
    {"word": "꽃잎", "en": "petal, delicate bloom"},
    {"word": "껍질", "en": "husk, outer layer"},
    {"word": "기포", "en": "air bubble, trapped breath"},
    {"word": "결정", "en": "crystal formation, ordered structure"},
    {"word": "파동", "en": "wave pattern, oscillating energy"},
    {"word": "공명", "en": "resonance, sympathetic vibration"},
    {"word": "메아리", "en": "echo, reflected sound"},
    {"word": "홀씨", "en": "dandelion seed, wind traveler"},
    {"word": "고치", "en": "cocoon, transformative shell"},
    {"word": "알", "en": "egg, embryonic potential"},
    {"word": "허물", "en": "shed skin, past form"},
    {"word": "만다라", "en": "mandala, geometric cosmos"},
    {"word": "프랙탈", "en": "fractal, self-similar infinity"},
    {"word": "엔트로피", "en": "entropy, inevitable disorder"},
    {"word": "황금비", "en": "golden ratio, divine proportion"},
    {"word": "클라인병", "en": "klein bottle, inside-out form"},
    {"word": "모비우스", "en": "mobius strip, infinite loop"},
    {"word": "자기장", "en": "magnetic field, invisible force"},
    {"word": "중력파", "en": "gravity wave, spacetime ripple"},
    {"word": "양자", "en": "quantum, probabilistic state"},
    {"word": "차원", "en": "dimension, spatial layer"},
    {"word": "소용돌이 은하", "en": "spiral galaxy, cosmic whirl"},
    {"word": "운석", "en": "meteorite, cosmic visitor"},
    {"word": "종유석", "en": "stalactite, mineral drip"},
    {"word": "갑옷", "en": "armor, protective shell"},
    {"word": "망토", "en": "cloak, concealing wrap"},
    {"word": "풍차", "en": "windmill, turning force"},
    {"word": "교차로", "en": "crossroads, decision point"},
    {"word": "비밀방", "en": "secret room, hidden space"},
    {"word": "수식", "en": "formula, mathematical truth"},
    {"word": "흉터", "en": "scar, healed wound"},
    {"word": "그물", "en": "net, capturing web"},
    {"word": "뼈", "en": "bone, structural support"},
    {"word": "씨방", "en": "seed pod, enclosed future"},
    {"word": "핵", "en": "nucleus, central core"},
    {"word": "분자", "en": "molecule, atomic bond"},
    {"word": "원자", "en": "atom, fundamental unit"},
    {"word": "잔상", "en": "afterimage, visual memory"},
    {"word": "애벌레", "en": "larva, pre-form stage"},
    {"word": "포자", "en": "spore, invisible spread"},
    {"word": "사향", "en": "musk, primal scent"},
    {"word": "피보나치", "en": "fibonacci spiral, nature sequence"},
    {"word": "카오스", "en": "chaos attractor, ordered disorder"},
    {"word": "오메가", "en": "omega, final point"},
    {"word": "알파", "en": "alpha, first beginning"},
    {"word": "레일", "en": "rail, guided track"},
    {"word": "지하철", "en": "subway, underground transit"},
    {"word": "로켓", "en": "rocket, upward thrust"},
    {"word": "수족관", "en": "aquarium, contained ocean"},
    {"word": "증기", "en": "steam, heated vapor"},
    {"word": "전류", "en": "current, flowing electricity"},
    {"word": "안테나", "en": "antenna, signal receiver"},
    {"word": "렌즈", "en": "lens, focusing optic"},
    {"word": "파도", "en": "wave, rhythmic surge"},
    {"word": "불씨", "en": "ember, dying spark"},
    {"word": "관절", "en": "joint, articulated connection"},
    {"word": "척추", "en": "spine, central column"},
    {"word": "발톱", "en": "claw, gripping talon"},
    {"word": "유기체", "en": "organism, living system"},
    {"word": "모래", "en": "sand, granular time"},
    {"word": "점토", "en": "clay, moldable earth"},
    {"word": "산맥", "en": "mountain range, geological spine"},
    {"word": "절벽", "en": "cliff, dramatic edge"},
    {"word": "정글", "en": "jungle, dense wilderness"},
    {"word": "낚시줄", "en": "fishing line, taut connection"},
    {"word": "덫", "en": "trap, hidden snare"},
    {"word": "뿌리채", "en": "root system, spreading grasp"},
    {"word": "피", "en": "blood, vital fluid"},
    {"word": "땀", "en": "sweat, exerted effort"},
    {"word": "뇌", "en": "brain, thinking center"},
    {"word": "기어", "en": "mechanical gear, interlocking teeth"},
    {"word": "유리창", "en": "glass pane, transparent barrier"},
    {"word": "철망", "en": "wire mesh, grid constraint"},
    {"word": "지진", "en": "earthquake, ground tremor"},
    {"word": "해일", "en": "tsunami, overwhelming surge"},
    {"word": "무지개", "en": "rainbow, spectral arc"},
    {"word": "혜성", "en": "comet, blazing trail"},
    {"word": "행성", "en": "planet, spherical world"},
    {"word": "위성", "en": "satellite, orbiting body"},
    {"word": "원반", "en": "disc, spinning form"},
    {"word": "소라", "en": "conch shell, spiral chamber"},
    {"word": "솔방울", "en": "pine cone, layered scales"},
    {"word": "전구", "en": "light bulb, illuminating moment"},
    {"word": "망원경", "en": "telescope, distant viewer"},
    {"word": "현미경", "en": "microscope, tiny revealer"},
    {"word": "진자", "en": "pendulum, rhythmic swing"},
    {"word": "용수철", "en": "spring coil, stored energy"},
    {"word": "피아노", "en": "piano, resonant keys"},
    {"word": "바이올린", "en": "violin, trembling string"},
    {"word": "드럼", "en": "drum, pounding rhythm"},
    {"word": "촛대", "en": "candleholder, ornate stand"},
    {"word": "모자", "en": "hat, crowning cover"},
    {"word": "신발", "en": "shoe, path-worn sole"},
    {"word": "반지", "en": "ring, circular bond"},
    {"word": "목걸이", "en": "necklace, adorning chain"},
    {"word": "나침반 바늘", "en": "compass needle, magnetic pointer"},
    {"word": "깃발", "en": "flag, wind-caught banner"},
    {"word": "배", "en": "ship, sea-crossing vessel"},
    {"word": "닻", "en": "anchor, holding weight"},
    {"word": "나선", "en": "helix, winding ascent"},
    {"word": "격자", "en": "lattice, crossing grid"},
    {"word": "균열", "en": "crack, fractured surface"},
    {"word": "소용돌이 구름", "en": "swirling cloud, atmospheric spiral"},
    {"word": "뿔", "en": "horn, protruding growth"},
    {"word": "집", "en": "house, sheltered space"},
    {"word": "성", "en": "castle, fortified dwelling"},
    {"word": "감옥", "en": "prison, confined space"},
    {"word": "온천", "en": "hot spring, mineral pool"},
    {"word": "협곡", "en": "canyon, eroded chasm"},
    {"word": "부두", "en": "dock, water's edge"},
    {"word": "광산", "en": "mine, underground extraction"},
    {"word": "방어막", "en": "shield, protective barrier"},
    {"word": "깃털 펜", "en": "quill pen, writing feather"}
]


def init_word_db():
    CONFIG_DIR.mkdir(parents=True, exist_ok=True)

    with open(WORD1_FILE, "w", encoding="utf-8") as f:
        json.dump(WORD1_DB, f, ensure_ascii=False, indent=2)
    total1 = sum(len(v) for v in WORD1_DB.values())
    print(f"[OK] word1-db.json: {len(WORD1_DB)}개 카테고리, {total1}개 단어")

    with open(WORD2_FILE, "w", encoding="utf-8") as f:
        json.dump(WORD2_POOL, f, ensure_ascii=False, indent=2)
    print(f"[OK] word2-pool.json: {len(WORD2_POOL)}개 단어")


if __name__ == "__main__":
    init_word_db()
